version: '3'
services:
  db:
    image: postgres:13
    restart: always
    container_name: pgdb
    env_file: ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    container_name: audio-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: audio-frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  pgdata: